
name: 'dbt_taboola_source'
version: '1.0.0'
config-version: 2

profile: 'dbt_taboola_source'

vars:
  dbt_taboola_source:
    account: "{{ source('taboola','account') }}"
    campaign: "{{ source('taboola','campaign') }}"
    campaign_item: "{{ source('taboola','campaign_item') }}"
    campaign_site_day_report: "{{ source('taboola','campaign_site_day_report') }}"
    campaign_type: "{{ source('taboola','campaign_type') }}"
    comment: "{{ source('taboola','comment') }}"
    content_provider_country_report: "{{ source('taboola','content_provider_country_report') }}"
    content_provider_platform_report: "{{ source('taboola','content_provider_platform_report') }}"
    country_report: "{{ source('taboola','country_report') }}"
    partner_type: "{{ source('taboola','partner_type') }}"
    platform_report: "{{ source('taboola','platform_report') }}"
    targeting_country: "{{ source('taboola','targeting_country') }}"
    targeting_os: "{{ source('taboola','targeting_os') }}"
    targeting_platform: "{{ source('taboola','targeting_platform') }}"
    targeting_sub_country: "{{ source('taboola','targeting_sub_country') }}"
    top_campaign_content_report: "{{ source('taboola','top_campaign_content_report') }}"
    taboola__account_passthrough_columns: []
    taboola__campaign_passthrough_columns: []
    taboola__campaign_item_passthrough_columns: []
    taboola__campaign_site_day_report_passthrough_columns: []
    taboola__campaign_type_passthrough_columns: []

models:
  dbt_taboola_source:
    tmp:
      materialized: view
    +materialized: table